const VENDORS=['SCALANCE','Eltex','Cisco','H3C','Huawei','MikroTik'];
const PROFILES={SCALANCE:'XC/XB/XP-200 · CLI V4.4 (руководство); V4.3.1 — сверять help',Eltex:'MES2300/3300/53xx · руководство ПО 6.6.13.4',Cisco:'Catalyst · IOS / IOS XE (не NX-OS)',H3C:'Коммутаторы · Comware 7',Huawei:'Коммутаторы · VRP (поддержка зависит от серии)',MikroTik:'RouterOS 7 · Bridge VLAN Filtering (не SwOS)'};
const SOURCES={SCALANCE:'https://cache.industry.siemens.com/dl/files/329/109817329/att_1130961/v1/PH_SCALANCE-XB-200-XC-200-XF-200BA-XP-200-XR-300WG-CLI_0.pdf',Eltex:'https://eltex.ru/storage/upload_center/files/17/MES_Series_user_manual_6.6.13.4.pdf',Cisco:'https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9500/software/release/17-14/command_reference/b_1714_9500_cr/b_1714_9500_cr.html',H3C:'https://www.h3c.com/en/Support/Resource_Center/EN/Home/Public/00-Public/Technical_Documents/Reference_Guides/Command_References/H3C_CR-19995/05/202410/2284492_294551_0.htm',Huawei:'https://support.huawei.com/enterprise/zh/doc/EDOC1100365027/2580a0e4/Interface%20Types.htm',MikroTik:'https://manual.mikrotik.com/docs/bridging-and-switching/'};
const TASKS=[];
function task(id,title,category,tags,description,commands,note='',mode='Просмотр: EXEC / display / терминал RouterOS'){TASKS.push({id,title,category,tags,description,commands,note,mode})}
function cmds(s,e,c,h,w,m){return Object.fromEntries(VENDORS.map((v,i)=>[v,[s,e,c,h,w,m][i]]).filter(x=>x[1]))}
task('ports','Проверить состояние портов','Интерфейсы','порт линк link speed duplex interface','Проверь физический линк, скорость и duplex. UP ещё не означает доступность IP.',cmds('show interfaces status','show interfaces status','show interfaces status','display interface brief','display interface brief','/interface ethernet print'));
task('port','Посмотреть конкретный интерфейс','Интерфейсы','порт ошибки crc counters','Смотри состояние, счётчики ошибок и согласованную скорость. Номера портов — примеры.',cmds('show interfaces fastethernet 0/1','show interfaces gigabitethernet 1/0/1','show interfaces GigabitEthernet1/0/1','display interface GigabitEthernet1/0/1','display interface GigabitEthernet0/0/1','/interface ethernet monitor ether1 once'));
task('vlan','Посмотреть VLAN','VLAN','vlan влан список','Найди VLAN и его участников. Само наличие VLAN не гарантирует прохождение по аплинкам.',cmds('show vlan','show vlan','show vlan brief','display vlan','display vlan','/interface bridge vlan print'));
task('membership','Проверить VLAN на портах','VLAN','tagged untagged pvid trunk native проброс','Сравни членство VLAN, PVID и обработку тегов на обоих концах линка.',cmds('show vlan port config','show interfaces switchport','show interfaces switchport\nshow interfaces trunk','display port trunk\ndisplay vlan 120','display port vlan','/interface bridge port print\n/interface bridge vlan print'));
task('mac','Найти изученные MAC','Диагностика','mac таблица устройство поиск','MAC изучается по адресу источника входящего кадра. Проверяй нужный VLAN и порт.',cmds('show mac-address-table','show mac address-table','show mac address-table','display mac-address','display mac-address','/interface bridge host print'));
task('arp','Найти MAC по IP','Маршрутизация','arp ip mac сосед','ARP-таблица показывает соседей IPv4 в локальных сегментах устройства. Для удалённого IP ищи на его шлюзе.',cmds('show ip arp','show arp','show ip arp','display arp','display arp','/ip arp print'));
task('lldp','Посмотреть соседние коммутаторы','Диагностика','lldp сосед схема топология','Сопоставь локальный порт с именем и портом соседа. Отсутствие LLDP не доказывает отсутствие линка.',cmds('show lldp neighbors','show lldp neighbors','show lldp neighbors','display lldp neighbor-information','display lldp neighbor brief','/ip neighbor print'));
task('stp','Проверить STP / RSTP','Резервирование','stp rstp mstp blocking петля root','Найди root bridge, роли портов и блокировки. Заблокированный резервный порт может быть нормой.',cmds('show spanning-tree','show spanning-tree','show spanning-tree','display stp brief','display stp brief','/interface bridge monitor bridge1 once'));
task('mrp','Проверить промышленное кольцо','Резервирование','mrp ring hrp кольцо open active manager','Проверь протокол, роль менеджера и ring ports. Active у менеджера может означать открытие резервного пути при разрыве.',cmds('show ring-redundancy',null,null,null,null,null),'Для этих SCALANCE команда относится к ring redundancy. Поддержку MRP нельзя переносить на все серии других вендоров.');
task('mrpcounter','Посмотреть переключения кольца','Резервирование','mrp manager counters разрыв переключение','Сопоставь число переключений с временем аварии и журналом событий.',cmds('show ring-redundancy manager counters',null,null,null,null,null));
task('lacp','Проверить агрегацию','Резервирование','lacp lag etherchannel bond port channel','Проверь участвующие порты и состояние партнёра. Один поток обычно не использует суммарную скорость всех линков.',cmds('show lacp neighbor detail\nshow lacp counters','show lacp port-channel','show etherchannel summary','display link-aggregation verbose','display eth-trunk','/interface bonding monitor bond1 once'));
task('config','Посмотреть текущую конфигурацию','Система','config конфиг running backup','Это рабочая конфигурация. Перед изменениями сохрани копию и сравни с загружаемой после перезапуска.',cmds('show running-config','show running-config','show running-config','display current-configuration','display current-configuration','/export'));
task('save','Сохранить конфигурацию','Система','сохранить write save startup','Сохрани проверенные изменения, чтобы они сохранились после перезапуска.',cmds('write startup-config','copy running-config startup-config','copy running-config startup-config','save','save','/system backup save name=before-change'),'RouterOS применяет и сохраняет настройки автоматически; backup здесь создаёт отдельный бинарный снимок. Comware/VRP могут запросить подтверждение.','EXEC # / user view; RouterOS — терминал');
task('logs','Посмотреть журнал событий','Диагностика','logs syslog логи флап flap','Ищи время смены состояния порта, кольца и перезагрузки. Проверь синхронизацию часов.',cmds('show logbook','show logging','show logging','display logbuffer','display logbuffer','/log print'));
task('version','Узнать версию и модель','Система','version firmware прошивка модель','Запиши точную модель и версию ПО перед выбором синтаксиса.',cmds('show device information','show version','show version','display version','display version','/system resource print'));
task('ip','Посмотреть IP-интерфейсы','Маршрутизация','svi gateway vlan interface адрес','Проверь адреса и состояние SVI. IP управления L2-коммутатора не делает его маршрутизатором между VLAN.',cmds('show ip interface','show ip interface','show ip interface brief','display ip interface brief','display ip interface brief','/ip address print'));
task('route','Посмотреть таблицу маршрутов','Маршрутизация','route маршрут default gateway','Ищи маршрут к адресу назначения и next hop. Побеждает наиболее длинный совпавший префикс.',cmds(null,'show ip route','show ip route','display ip routing-table','display ip routing-table','/ip route print'),'L3-функции зависят от модели и лицензии. Для XC200 не подставляем команды L3-серий.');
task('ping','Проверить доступность IPv4','Диагностика','ping icmp пинг','Успешный ping проверяет ICMP-путь в обе стороны. Неуспешный может быть следствием фильтрации.',cmds('ping 10.120.0.10','ping 10.120.0.10','ping 10.120.0.10','ping 10.120.0.10','ping 10.120.0.10','/ping 10.120.0.10 count=4'));
task('ntp','Проверить синхронизацию времени','Сервисы','ntp время часы','Сравни время устройства с сервером: это нужно для сопоставления событий.',cmds('show ntp info','show sntp status\nshow sntp configuration','show ntp associations','display ntp-service status','display ntp-service status','/system ntp client print'));
task('igmp','Посмотреть multicast-группы','Мультикаст','igmp snooping multicast группы','Проверь группу, VLAN и порты подписчиков. Затем проверь наличие querier.',cmds('show ip igmp snooping groups','show ip igmp snooping groups','show ip igmp snooping groups','display igmp-snooping group','display igmp-snooping port-info','/interface bridge mdb print'));
task('sfp','Проверить оптический модуль','Интерфейсы','sfp ddm dom rx tx оптика transceiver','Сравни Rx/Tx и пороги конкретного модуля. DDM доступен не у каждого SFP.',cmds(null,'show fiber-ports optical-transceiver','show interfaces transceiver detail','display transceiver diagnosis interface GigabitEthernet1/0/1','display transceiver diagnosis interface GigabitEthernet0/0/1','/interface ethernet monitor sfp-sfpplus1 once'),'Для SCALANCE используй диагностику SFP в WBM конкретной модели; неподтверждённую CLI-команду не подставляем.');
task('vrrp','Проверить резервирование шлюза','Маршрутизация','vrrp master backup gateway шлюз','Сверь VRID, виртуальный IP, роль и priority на обоих узлах.',cmds(null,'show vrrp brief','show vrrp brief','display vrrp verbose','display vrrp brief','/interface vrrp print detail'),'Только устройства с поддержкой VRRP. Eltex: по руководству MES 6.6.13.4, только для моделей с VRRP.');
task('ospf','Проверить соседей OSPF','Маршрутизация','ospf neighbor routing соседство','Проверь состояние соседства и интерфейс. Для двух DROTHER на broadcast-сегменте 2-Way может быть нормой.',cmds(null,null,'show ip ospf neighbor','display ospf peer','display ospf peer','/routing ospf neighbor print'),'OSPF — для поддерживаемых L3-моделей.');
task('nat','Посмотреть правила NAT/PAT','Маршрутизация','nat pat masquerade трансляция','Отдельно проверь правила, счётчики и соединения. NAT не заменяет маршрут и разрешение firewall.',cmds(null,null,null,null,null,'/ip firewall nat print stats'),'RouterOS: NAT на маршрутизаторе. Для Catalyst, MES и XC200 не предполагаем наличие NAT.');
task('create','Создать VLAN 120','VLAN','vlan создать office','Создай новый VLAN. В RouterOS пример добавляет запись для уже существующего bridge1 и двух аплинков.',cmds('vlan 120\nname OFFICE','vlan database\nvlan 120 name OFFICE\nexit','vlan 120\nname OFFICE','vlan 120\nname OFFICE','vlan 120\ndescription OFFICE','/interface bridge vlan add bridge=bridge1 vlan-ids=120 tagged=ether1,ether2'),'SCALANCE: только 802.1Q VLAN Bridge; FastEthernet/GigabitEthernet выбирай по модели и порту. RouterOS: bridge и порты уже существуют, VLAN filtering настроен; повторный add не нужен для существующей записи.','Режим конфигурации → VLAN; RouterOS — терминал');
task('trunk','Добавить VLAN в существующий тракт','VLAN','проброс add tagged trunk аплинк','Пример для уже настроенного trunk. Добавь VLAN на обоих концах каждого используемого линка.',cmds('vlan 120\nports fastethernet 0/1-2','interface gigabitethernet 1/0/1\nswitchport trunk allowed vlan add 120','interface GigabitEthernet1/0/1\nswitchport trunk allowed vlan add 120','interface GigabitEthernet1/0/1\nport trunk permit vlan 120','interface GigabitEthernet0/0/1\nport trunk allow-pass vlan 120','/interface bridge vlan set [find bridge=bridge1 vlan-ids=120] tagged=ether1,ether2'),'SCALANCE: ports ЗАМЕНЯЕТ список в VLAN 120. Пример для нового VLAN и двух tagged-портов; при существующем VLAN перечисли всех нужных участников. Cisco/Eltex: add сохраняет прежние VLAN. PVID аплинков для нового tagged VLAN менять не надо. RouterOS: VLAN 120 уже существует; set заменяет полный список tagged. Сохрани всех прежних участников, включая bridge1, если CPU уже участвует.','Глобальная конфигурация → VLAN / интерфейс');
task('access','Назначить конечный порт VLAN 120','VLAN','access untagged pvid конечный','Пример для нового VLAN и порта устройства без тегов. Аплинки в примере — tagged.',cmds('vlan 120\nports fastethernet 0/1-2 untagged fastethernet 0/3\nexit\ninterface fastethernet 0/3\nswitchport pvid 120','interface gigabitethernet 1/0/5\nswitchport mode access\nswitchport access vlan 120','interface GigabitEthernet1/0/5\nswitchport mode access\nswitchport access vlan 120','interface GigabitEthernet1/0/5\nport link-type access\nport access vlan 120','interface GigabitEthernet0/0/5\nport link-type access\nport default vlan 120','/interface bridge vlan set [find bridge=bridge1 vlan-ids=120] tagged=ether1,ether2 untagged=ether5\n/interface bridge port set [find interface=ether5] pvid=120'),'SCALANCE: перечисли полный состав VLAN в ports. До изменения конечного порта проверь его прежнее назначение. RouterOS: VLAN 120 уже создан; set задаёт полный состав этой записи, перечисли всех участников.','Глобальная конфигурация → VLAN / интерфейс');
task('enter','Войти в режим конфигурации','Система','enable configure terminal system view','Команды ниже меняют режим CLI, но сами по себе не меняют настройки сети.',cmds('enable\nconfigure terminal','enable\nconfigure terminal','enable\nconfigure terminal','system-view','system-view',null),'RouterOS использует меню и абсолютные пути команд, отдельного configure terminal нет.','Из начального приглашения CLI');
task('portconfig','Посмотреть конфигурацию порта','Интерфейсы','running current interface config порт','Сравни режим порта, разрешённые VLAN и параметры с соседним устройством.',cmds('show running-config','show running-config interfaces gigabitethernet 1/0/1','show running-config interface GigabitEthernet1/0/1','display current-configuration interface GigabitEthernet1/0/1','display current-configuration interface GigabitEthernet0/0/1','/interface bridge port print detail'),'SCALANCE: найди блок нужного интерфейса в выводе.');
task('fault','Проверить сигнал неисправности','Диагностика','fault alarm сигнал авария','Для SCALANCE проверь текущие faults: питание, контролируемые порты и другие события.',cmds('show events faults status',null,null,null,null,null));
const PROTOCOLS=[
['802.1Q / VLAN','VLAN','Метка VLAN разделяет широковещательные домены. Tagged сохраняет метку на выходе, untagged снимает. PVID определяет VLAN входящего кадра без метки.','membership'],
['STP / RSTP / MSTP','Резервирование','Предотвращают L2-петли. RSTP быстрее сходится; MSTP объединяет VLAN в экземпляры. Проверяй root и роли портов.','stp'],
['MRP','Резервирование','Резервирование промышленного кольца. Менеджер управляет резервным трактом; при разрыве обеспечивает обход. VLAN должен проходить по обоим возможным путям.','mrp'],
['LACP','Резервирование','Согласует агрегацию линков. Проверяй партнёра и участвующие порты; VLAN обычно настраиваются на логическом агрегате.','lacp'],
['LLDP','Диагностика','Обмен сведениями о соседях на одном линке. Помогает восстановить физическую схему.','lldp'],
['VRRP','Маршрутизация','Резервирует виртуальный шлюз внутри сегмента. Хосты используют один виртуальный IP; роль Master может перейти к Backup.','vrrp'],
['OSPF','Маршрутизация','Динамическая маршрутизация по состоянию каналов. Сначала проверь соседство, затем маршруты.','ospf'],
['RIP','Маршрутизация','Дистанционно-векторная маршрутизация; метрика — число переходов. Максимальный рабочий путь 15 hops.','route'],
['Статические маршруты / SVI','Маршрутизация','SVI — L3-интерфейс VLAN. Для связи между VLAN нужны маршрутизация, корректные шлюзы и разрешающие политики.','route'],
['NAT / PAT','Маршрутизация','NAT меняет адреса; PAT дополнительно использует порты, чтобы несколько соединений делили внешний адрес. Обычно это функция пограничного маршрутизатора.','nat'],
['ACL','Безопасность','Правила разрешения и запрета трафика. Важны порядок правил, направление и место применения.','portconfig'],
['DHCP / Relay','Сервисы','DHCP выдаёт адрес, маску и другие параметры. Relay передаёт запросы к серверу из другого IP-сегмента.','ip'],
['DNS','Сервисы','Преобразует имена в адреса. Если IP доступен, а имя нет — проверь DNS отдельно.','ping'],
['NTP / SNTP','Сервисы','Синхронизируют часы; помогают сравнивать время аварии на разных устройствах.','ntp'],
['SNMP','Сервисы','Позволяет мониторить состояние, счётчики и события. SNMPv3 поддерживает аутентификацию и шифрование.','config'],
['Syslog','Сервисы','Отправляет журналы на общий сервер. Нужны корректное время и достижимость сервера.','logs'],
['SSH / Telnet','Сервисы','SSH шифрует управление. Telnet передаёт данные открыто; учитывай это при выборе доступа.','enter'],
['TFTP / SFTP','Сервисы','Передача конфигураций и файлов. TFTP не предоставляет защиты SSH; SFTP работает поверх SSH.','save'],
['IGMP / Snooping / Querier','Мультикаст','IGMP сообщает о подписчиках IPv4 multicast. Snooping ограничивает L2-рассылку; querier поддерживает актуальность подписок.','igmp'],
['QinQ','VLAN','Добавляет внешнюю VLAN-метку поверх внутренней. Проверяй MTU и поддержку оборудования.','membership'],
['Port Security / Storm Control','Безопасность','Ограничивают MAC и лавину broadcast/multicast/unknown unicast. Срабатывание защиты может объяснять потерю связи.','port'],
['SPAN / Port Mirroring','Диагностика','Копирует трафик на порт анализатора. Проверь направление и загрузку: зеркало может терять пакеты.','portconfig'],
['PROFINET','Промышленные','Промышленный Ethernet; использует IP для части функций и прямую L2-передачу для RT. RT-трафик нельзя считать обычным TCP-потоком.','lldp'],
['Modbus TCP','Промышленные','Обмен запросами и ответами поверх TCP, обычно порт 502. Отдельно проверяй TCP-соединение и ответы приложения.','ping'],
['PROFIBUS','Промышленные','Полевая шина, не Ethernet VLAN. Диагностика требует проверки шины, терминаторов и адресов станций.','fault'],
['PTP / IEEE 1588','Промышленные','Точная синхронизация времени. Поддержка transparent/boundary clock и профиля зависит от модели.','ntp'],
['PRP / HSR','Промышленные','Передают дубли кадров по резервным путям и удаляют повтор на приёмнике. Требуют совместимых узлов и топологии.','mrp'],
['Loop Detection','Диагностика','Обнаруживает петли по механизмам конкретного вендора. Отличай от STP и не снимай блокировку, пока причина петли не устранена.','stp']
].map(([title,category,description,related],i)=>({id:'protocol-'+i,title,category,description,related,tags:title+' протокол функция'}));

TASKS.find(t=>t.id==="portconfig").examTitle={Eltex:"Посмотреть текущую конфигурацию порта Gi1/0/1",Cisco:"Посмотреть текущую конфигурацию порта Gi1/0/1",H3C:"Посмотреть текущую конфигурацию порта Gi1/0/1",Huawei:"Посмотреть текущую конфигурацию порта Gi0/0/1"};
TASKS.find(t=>t.id==="portconfig").examMode={Eltex:"Просмотр · привилегированный EXEC (#)"};
