const DOC={
console:'https://help.mikrotik.com/docs/spaces/ROS/pages/328155/Configuration+Management',
vlan:'https://help.mikrotik.com/docs/spaces/ROS/pages/28606465/Bridge+VLAN+Table',
ntp:'https://help.mikrotik.com/docs/spaces/ROS/pages/40992869/NTP',
nat:'https://help.mikrotik.com/docs/spaces/ROS/pages/3211299/NAT',
ospf:'https://help.mikrotik.com/docs/spaces/ROS/pages/9863229/OSPF',
vrrp:'https://help.mikrotik.com/docs/spaces/ROS/pages/81362945/VRRP',
route:'https://help.mikrotik.com/docs/spaces/ROS/pages/328084/IP+Routing',
log:'https://help.mikrotik.com/docs/spaces/ROS/pages/328094/Log',
backup:'https://help.mikrotik.com/docs/spaces/ROS/pages/40992852/Backup',
snmp:'https://help.mikrotik.com/docs/spaces/ROS/pages/8978519/SNMP',
ciscoInterface:'https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-8/command_reference/b_178_9300_cr/interface_and_hardware_commands.html',
ciscoReload:'https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-12/configuration_guide/sys_mgmt/b_1712_sys_mgmt_9300_cg/performing_device_setup_configuration.html',
ciscoReplace:'https://www.cisco.com/c/en/us/td/docs/ios/ios_xe/fundamentals/configuration/guide/TIPs_conversion/config_mgmt_xe_3s_Book/cf_config-rollback_xe.html',
h3cRollback:'https://www.h3c.com/en/Support/Resource_Center/EN/Home/Public/00-Public/Technical_Documents/Reference_Guides/Command_References/H3C_CR-20108/01/202406/2204873_294551_0.htm',
huaweiRollback:'https://info.support.huawei.com/enterprise/en/doc/EDOC1100419273/7cea5c40/managing-configuration-files',
dai:'https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-18/configuration_guide/sec/b_1718_sec_9300_cg/configuring_dynamic_arp_inspection.html',
wireshark:'https://www.wireshark.org/docs/wsug_html/'
};
function addTask(id,title,category,tags,description,commands,note='',mode='Просмотр: EXEC / терминал'){task(id,title,category,tags,description,commands,note,mode);return TASKS.at(-1)}
addTask('hsrp','Проверить HSRP на Cisco','Резервирование','hsrp standby active standby gateway','HSRP использует роли Active/Standby. Сверь группу, виртуальный IP, priority и tracking. Это отдельный протокол, а не другое имя VRRP.',{Cisco:'show standby brief'});
addTask('cpu-vlan','Доступ к CPU / L3 в VLAN на MikroTik','VLAN','bridge cpu tagged управление svi','Для доступа к самому RouterOS в VLAN 120 bridge1 участвует как CPU-порт. Пример для уже существующей записи VLAN и настроенного bridge.',{MikroTik:'/interface bridge vlan set [find bridge=bridge1 vlan-ids=120] tagged=bridge1,ether1,ether2\n/interface vlan add name=vlan120 interface=bridge1 vlan-id=120\n/ip address add address=10.120.0.2/24 interface=vlan120'},'set задаёт полный tagged-список: сохрани всех участников. VLAN-интерфейс и IP добавляй только если их ещё нет. Доступ зависит также от firewall и IP service. Для чистого L2-транзита CPU-членство не требуется.','RouterOS — терминал; изменение конфигурации');
addTask('errors','Отдельно проверить счётчики ошибок','Диагностика','crc counters errors drops','Сравни прирост за одинаковый интервал. Не очищай счётчики перед фиксацией исходного состояния.',{Cisco:'show interfaces counters errors',Eltex:'show interfaces counters',MikroTik:'/interface ethernet print stats'});
addTask('poe','Проверить PoE и бюджет питания','Диагностика','poe power inline питание','Сверь состояние порта и суммарный бюджет PoE. Команда применима только к моделям с соответствующим PoE.',{Cisco:'show power inline',Eltex:'show power inline'});
addTask('resources','Проверить CPU и память','Диагностика','cpu memory ram нагрузка','Сопоставь нагрузку CPU/памяти с моментом сбоя. Высокая CPU не обязательно означает перегрузку аппаратного forwarding.',{Cisco:'show processes cpu sorted\nshow processes memory sorted',Eltex:'show cpu utilization',MikroTik:'/system resource print\n/tool profile'},'Eltex: здесь загрузка CPU; команда подробной памяти требует сверки модели. RouterOS tool profile работает до остановки Ctrl+C.');
addTask('errdisable','Найти порт в err-disable','Безопасность','err-disable errdisabled recovery','Сначала найди причину в журнале и настройках защиты. Восстановление порта без устранения причины может снова отключить его.',{Cisco:'show interfaces status err-disabled\nshow errdisable recovery\nshow logging'});
addTask('security','Проверить Port Security','Безопасность','port-security violation sticky mac','Сверь число разрешённых MAC, learned/sticky MAC и причину violation. Удаление защиты не является диагностикой.',{Cisco:'show port-security interface GigabitEthernet1/0/5'});
addTask('storm','Проверить Storm Control','Безопасность','storm-control broadcast multicast','Сверь порог, действие и счётчики. Порог должен соответствовать ожидаемой нагрузке сервиса.',{Cisco:'show storm-control',Eltex:'show storm-control'});
addTask('acl','Посмотреть ACL и счётчики','Безопасность','acl access-list match counters firewall','Проверь порядок правил и точку применения. Доступность счётчиков аппаратного ACL зависит от модели.',{Cisco:'show access-lists',MikroTik:'/ip firewall filter print stats'},'RouterOS firewall и ACL коммутатора — разные механизмы. Нулевой счётчик не всегда означает, что трафик не проходил аппаратный тракт.');
addTask('snooping','Проверить DHCP Snooping и DAI','Безопасность','dhcp snooping dai arp inspection binding','Сверь VLAN, trusted-порты и DHCP bindings; DAI использует доверенные привязки и настройки проверки ARP.',{Cisco:'show ip dhcp snooping\nshow ip dhcp snooping binding\nshow ip arp inspection statistics'},'Для статических IP нужна подходящая разрешающая привязка/ARP ACL по документации. Не отмечай все аплинки trusted автоматически.');
addTask('description','Задать описание порта','Настройка','description comment порт','Пример имени соседа и порта. Подставь фактическое подключение.',{Cisco:'interface GigabitEthernet1/0/5\ndescription TO-SW2-GI1/0/1',Eltex:'interface gigabitethernet 1/0/5\ndescription TO-SW2-GI1/0/1',H3C:'interface GigabitEthernet1/0/5\ndescription TO-SW2-GI1/0/1',Huawei:'interface GigabitEthernet0/0/5\ndescription TO-SW2-GI0/0/1',MikroTik:'/interface ethernet set [find name=ether5] comment=TO-SW2'},'Сначала войди в режим конфигурации соответствующей ОС.','Режим глобальной конфигурации → интерфейс / RouterOS');
addTask('shutdown','Административно выключить порт','Настройка','shutdown disabled отключить','Команда выключает выбранный порт. До применения проверь, не является ли он путём управления или рабочим аплинком.',{Cisco:'interface GigabitEthernet1/0/5\nshutdown',Eltex:'interface gigabitethernet 1/0/5\nshutdown',H3C:'interface GigabitEthernet1/0/5\nshutdown',Huawei:'interface GigabitEthernet0/0/5\nshutdown',MikroTik:'/interface ethernet set [find name=ether5] disabled=yes'},'Это изменение, а не просмотр. Используй план возврата доступа.','Глобальная конфигурация → интерфейс / RouterOS');
addTask('noshutdown','Административно включить порт','Настройка','no shutdown undo disabled включить','Сначала устрани причину отключения, особенно при срабатывании защиты.',{Cisco:'interface GigabitEthernet1/0/5\nno shutdown',Eltex:'interface gigabitethernet 1/0/5\nno shutdown',H3C:'interface GigabitEthernet1/0/5\nundo shutdown',Huawei:'interface GigabitEthernet0/0/5\nundo shutdown',MikroTik:'/interface ethernet set [find name=ether5] disabled=no'},'При Cisco err-disable после устранения причины может потребоваться shutdown/no shutdown.','Глобальная конфигурация → интерфейс / RouterOS');
addTask('svi','Назначить IP на SVI','Настройка','svi ip vlan gateway управление','Пример IP-интерфейса VLAN 120. Это не включает автоматически маршрутизацию между VLAN и не создаёт маршрут по умолчанию.',{Cisco:'interface Vlan120\nip address 10.120.0.1 255.255.255.0\nno shutdown',Eltex:'interface vlan 120\nip address 10.120.0.1 /24\nno shutdown',H3C:'interface Vlan-interface120\nip address 10.120.0.1 255.255.255.0',Huawei:'interface Vlanif120\nip address 10.120.0.1 255.255.255.0'},'Только поддерживаемые модели. VLAN уже создан; адрес должен быть свободен. UP зависит от условий активности VLAN. Если это шлюз хостов, маршрутизация и политики должны быть настроены отдельно.','Глобальная конфигурация → SVI');
addTask('static','Добавить статический маршрут','Настройка','route static next hop маршрут','Маршрут к 10.130.0.0/24 через достижимый next hop 10.120.0.254. Проверь также обратный маршрут.',{Cisco:'ip route 10.130.0.0 255.255.255.0 10.120.0.254',H3C:'ip route-static 10.130.0.0 255.255.255.0 10.120.0.254',Huawei:'ip route-static 10.130.0.0 255.255.255.0 10.120.0.254',MikroTik:'/ip route add dst-address=10.130.0.0/24 gateway=10.120.0.254'},'Только L3-устройства. Это учебные адреса; повторный add может создать лишнюю запись.','Глобальная конфигурация / RouterOS');
addTask('defaultgw','Настроить шлюз управления L2 Cisco','Настройка','default gateway l2 management','Пример default gateway для L2 Catalyst с выключенной IP-маршрутизацией. Адрес шлюза должен быть в подсети управления.',{Cisco:'ip default-gateway 10.120.0.254'},'При включённом ip routing нужен маршрут по умолчанию, а не этот механизм. Не меняй адрес шлюза без проверки возврата доступа.','Глобальная конфигурация');
addTask('lag-config','Пример настройки LACP Cisco','Настройка','lacp channel-group port-channel active','Пример двух свободных и совместимых портов к одному логическому партнёру. VLAN на агрегате настраиваются отдельно.',{Cisco:'interface range GigabitEthernet1/0/1 - 2\nchannel-group 1 mode active\nexit\ninterface Port-channel1\nswitchport mode trunk'},'Не переноси занятые порты в LAG без плана. Сверь настройки на другом конце и полный allowed VLAN на Port-channel1.','Глобальная конфигурация');
addTask('rstp-config','Пример включения RSTP','Настройка','rstp spanning-tree rapid pvst','Изменение протокола затрагивает топологию. Cisco Rapid-PVST — RSTP по VLAN; RouterOS RSTP работает в bridge.',{Cisco:'spanning-tree mode rapid-pvst',MikroTik:'/interface bridge set [find name=bridge1] protocol-mode=rstp'},'Не применяй автоматически в MRP-кольце. Согласуй root, совместимость и роли портов.','Глобальная конфигурация / RouterOS');
addTask('mirror','Зеркалирование порта Cisco','Настройка','span monitor session mirror wireshark','Пример копирования Rx/Tx Gi1/0/5 на выделенный Gi1/0/24 для анализатора.',{Cisco:'monitor session 1 source interface GigabitEthernet1/0/5 both\nmonitor session 1 destination interface GigabitEthernet1/0/24'},'Session 1 и порт назначения должны быть свободны. Порт назначения перестаёт быть обычным рабочим портом. Удаление созданной сессии: no monitor session 1.','Глобальная конфигурация');
addTask('syslog-config','Отправлять Syslog на сервер','Настройка','syslog logging remote','Пример сервера 10.120.0.50: проверь путь, часы и принимаемый уровень сообщений.',{Cisco:'logging host 10.120.0.50\nlogging trap informational',MikroTik:'/system logging action add name=remote-log target=remote remote=10.120.0.50\n/system logging add topics=info action=remote-log'},'RouterOS: имя action должно быть свободно. Уровни/topics подбирай под события; info не заменяет остальные категории.','Глобальная конфигурация / RouterOS');
addTask('ntp-config','Назначить NTP-сервер','Настройка','ntp sntp clock server','Пример доверенного сервера времени 10.120.0.50.',{Cisco:'ntp server 10.120.0.50',Eltex:'sntp server 10.120.0.50',MikroTik:'/system ntp client set enabled=yes\n/system ntp client servers add address=10.120.0.50'},'Проверь достижимость и фактическое synchronized/selected-server. RouterOS: не добавляй существующую запись повторно. Eltex: режим клиента сверяй с текущей конфигурацией.','Глобальная конфигурация / RouterOS');
addTask('snmp-check','Проверить настройки SNMP','Сервисы','snmp monitoring zabbix','Проверь доступность агента, версию и ограничения источников. Секреты могут попадать в конфигурационный вывод.',{Cisco:'show snmp',MikroTik:'/snmp print\n/snmp community print'},'Для создания SNMPv3 нужны согласованные user/group, права и auth/privacy. Универсальный шаблон с общим паролем не используем.');
addTask('ssh-check','Проверить SSH-доступ','Сервисы','ssh vty ip service','Проверь, что служба слушает и вход разрешён нужным администраторам.',{Cisco:'show ip ssh\nshow running-config | section line vty',MikroTik:'/ip service print where name=ssh'},'Включение SSH требует локальной/AAA-аутентификации, ключей и правил доступа по конкретной ОС. Проверку TCP-порта 22 делай также с административного хоста.');
addTask('export','Сохранить текстовую копию RouterOS','Откат','backup export safe configuration','Export удобен для сравнения и аудита; бинарный backup и export решают разные задачи.',{MikroTik:'/export file=before-change'},'Скачай .rsc на свой компьютер. Export не является полным снимком всех файлов/ключей. Не включай show-sensitive для пересылки файла.');
addTask('reloadtimer','Cisco: перезагрузка по таймеру','Откат','reload in cancel rollback страховка','В согласованное окно таймер может вернуть сохранённую startup-config после потери доступа. Это перезагрузка с прерыванием трафика, а не безразрывный откат.',{Cisco:'reload in 5'},'До запуска проверь startup-config, boot и доступ через консоль. На запрос сохранения не записывай непроверенные изменения. При успешной проверке отдельно выполни reload cancel, проверь show reload, затем сохрани конфигурацию. Пять минут — учебный интервал; он может оказаться слишком коротким.').quiz=false;
addTask('reloadcancel','Cisco: отменить таймер перезагрузки','Откат','reload cancel show reload','После подтверждения доступа отмени ранее запланированную перезагрузку и проверь её состояние.',{Cisco:'reload cancel\nshow reload'}).quiz=false;
addTask('replaceconfig','Восстановить проверенную конфигурацию','Откат','configure replace rollback file','Команда заменяет текущую конфигурацию заранее подготовленным совместимым файлом. Она способна изменить управление и рабочий трафик.',{Cisco:'configure replace flash:before-change.cfg',H3C:'configuration replace file flash:/before-change.cfg'},'Файл должен существовать на устройстве и быть создан/проверен для этой ОС. Это отдельная операция возврата, не команда страховки сама по себе. Cisco configure replace поддерживается не всеми платформами; H3C — по руководству Comware 7 указанного семейства.').quiz=false;
const SAFE_MODE_NOTE='RouterOS: Ctrl+X или F4 включает Safe Mode; приглашение содержит SAFE. При аварийном завершении сессии защищённые изменения откатываются после обработки потери сессии. Ctrl+X после успешной проверки освобождает Safe Mode и сохраняет изменения; Ctrl+D отменяет их. Есть лимит журнала изменений; следи, что SAFE остаётся активным. Это клавиши терминала, не строка команды.';
const HUAWEI_ROLLBACK_NOTE='Huawei: rollback configuration to file подтверждён в руководстве NetEngine 8000 V800R024, а не для всех S5700 VRP. На коммутатор его автоматически не переносим. Уточни модель, версию и наличие механизма commit/rollback; безопасный план нужен до изменения.';
const extraProtocols=[
['HSRP','Резервирование','Cisco-протокол виртуального шлюза с ролями Active/Standby. Выбирай HSRP или VRRP по требованиям и поддержке, а не только по вендору.','hsrp'],
['802.1X','Безопасность','Контроль доступа к порту через supplicant, authenticator и сервер AAA/RADIUS. Физический UP не означает, что клиент авторизован.','portconfig'],
['DHCP Snooping','Безопасность','Проверяет DHCP-обмен и строит bindings. Trusted указывает доверенный путь к серверу; неверная настройка может блокировать выдачу адреса.','snooping'],
['DAI','Безопасность','Dynamic ARP Inspection проверяет ARP по доверенным привязкам и политикам. Статические IP требуют отдельного учёта.','snooping'],
['QoS · 802.1p / DSCP','Промышленные','802.1p — PCP в VLAN-теге L2; DSCP — метка в IP L3. Доверие меткам, очереди и mapping настраиваются отдельно. Для PROFINET сверяй класс трафика и рекомендации устройств.','portconfig'],
['MTU / Jumbo','Интерфейсы','MTU должен согласовываться по пути. Учитывай, что CLI может показывать L3 MTU или размер L2-кадра с другим учётом заголовков. Jumbo требует поддержки всего тракта.','port'],
['BGP','Маршрутизация','Обменивается маршрутами и атрибутами политики между автономными системами и внутри AS. Сначала проверь соседство, затем объявленные и принятые префиксы.','route'],
['ECMP','Маршрутизация','Несколько равноценных next hop. Распределение обычно зависит от хэша потока; один поток не обязан использовать все пути.','route']
];extraProtocols.forEach(([title,category,description,related],i)=>PROTOCOLS.push({id:'extra-protocol-'+i,title,category,description,related,tags:title}));
const HOST_TASKS=[
{id:'host-ip',title:'IP, маска, интерфейсы',description:'Сверь адрес, маску, активный интерфейс и DNS.',commands:{Windows:'ipconfig /all\nGet-NetIPConfiguration',Linux:'ip -br address'},sources:{Windows:'https://learn.microsoft.com/en-us/powershell/module/nettcpip/get-netipconfiguration',Linux:'https://github.com/iproute2/iproute2/blob/main/man/man8/ip-address.8.in'}},
{id:'host-route',title:'Маршрут к серверу',description:'Проверь маршрут и исходящий интерфейс. Несколько адаптеров/VPN могут менять выбранный путь.',commands:{Windows:'route print',Linux:'ip route\nip route get 10.120.0.10'},sources:{Windows:'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/route_ws2008',Linux:'https://github.com/iproute2/iproute2/blob/main/man/man8/ip-route.8.in'}},
{id:'host-arp',title:'ARP и соседи',description:'Для удалённой подсети ищи MAC шлюза. ip neigh дополнительно показывает состояние соседства.',commands:{Windows:'arp -a',Linux:'ip neigh'},sources:{Windows:'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/arp',Linux:'https://github.com/iproute2/iproute2/blob/main/man/man8/ip-neighbour.8'}},
{id:'host-tcp',title:'Ping идёт, TCP-сервис нет',description:'Проверь именно порт 502. Успешный TCP connect ещё не означает правильный ответ Modbus.',commands:{Windows:'Test-NetConnection -ComputerName 10.120.0.10 -Port 502 -InformationLevel Detailed',Linux:'nc -vz -w 3 10.120.0.10 502'},sources:{Windows:'https://learn.microsoft.com/en-us/powershell/module/nettcpip/test-netconnection',Linux:'https://man.openbsd.org/nc'},note:'Windows — PowerShell. Linux: пример OpenBSD netcat; другие реализации nc могут иметь иной набор ключей.'},
{id:'host-listen',title:'Слушает ли сервер нужный порт',description:'Выполняй на сервере: сравни LISTEN, адрес привязки и процесс.',commands:{Windows:'Get-NetTCPConnection -State Listen | Select-Object LocalAddress,LocalPort,OwningProcess\nnetstat -ano',Linux:'sudo ss -tlnp'},sources:{Windows:'https://learn.microsoft.com/en-us/powershell/module/nettcpip/get-nettcpconnection',Linux:'https://github.com/iproute2/iproute2/blob/main/man/man8/ss.8'},note:'OwningProcess и последний столбец netstat -ano дают PID: сопоставь его с Get-Process -Id 1234, подставив фактический PID. sudo нужен для просмотра чужих процессов; 127.0.0.1 не принимает подключения с сети.'},
{id:'host-trace',title:'Посмотреть маршрут по hops',description:'Звёздочки могут означать фильтрацию ответов, а не обрыв передачи транзитного трафика.',commands:{Windows:'tracert -d 10.120.0.10',Linux:'tracepath -n 10.120.0.10'},sources:{Windows:'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/tracert',Linux:'https://github.com/iputils/iputils/blob/master/doc/tracepath.xml'}},
{id:'host-dns',title:'Проверить DNS отдельно',description:'Запроси A и AAAA реального имени. dig и Resolve-DnsName проверяют DNS, getent — системное разрешение имён, включая hosts/NSS. Для проверки конкретного DNS укажи -Server в PowerShell или @адрес в dig.',commands:{Windows:'Resolve-DnsName service.example.com -Type A -DnsOnly\nResolve-DnsName service.example.com -Type AAAA -DnsOnly\nnslookup service.example.com',Linux:'dig service.example.com A\ndig service.example.com AAAA\ngetent ahosts service.example.com'},sources:{Windows:'https://learn.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname',Linux:'https://bind9.readthedocs.io/en/latest/manpages.html#dig-dns-lookup-utility'}},
{id:'host-capture',title:'Снять трафик TCP-сервиса',description:'Краткий захват у клиента или сервера поможет сравнить запросы и ответы.',commands:{Linux:'sudo tcpdump -ni eth0 -c 100 -w service.pcap "host 10.120.0.10 and tcp port 502"',Windows:'pktmon start --capture --pkt-size 0\npktmon stop\npktmon etl2pcap PktMon.etl --out service.pcapng'},sources:{Linux:'https://www.tcpdump.org/manpages/tcpdump.1.html',Windows:'https://learn.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon'},note:'Linux: подставь свой интерфейс вместо eth0. Windows: start, воспроизведение ошибки, затем stop и конвертация — отдельные этапы; нужны права администратора. Захват Windows здесь без фильтра, может содержать другой трафик.'},
{id:'host-mtu',title:'IPv4 MTU: проверить пакет с DF',description:'Для IPv4 без опций payload 1472 + IP/ICMP 28 = 1500. Уменьшая размер, сравни результат в обе стороны.',commands:{Windows:'ping -f -l 1472 10.120.0.10',Linux:'ping -M do -s 1472 -c 4 10.120.0.10'},sources:{Windows:'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ping',Linux:'https://github.com/iputils/iputils/blob/master/doc/ping.xml'},note:'Неответ не доказывает MTU: ICMP может фильтроваться. Linux — iputils ping; проверяй поддержку параметров.'}
];
const COMMAND_INFO={};
function evidence(ids,vendor,source,label,status='По руководству; на устройстве не проверено'){for(const id of ids.split(' '))(COMMAND_INFO[id] ||= {})[vendor]={source,label,status}}
function commandInfo(t,v){return COMMAND_INFO[t.id]?.[v]||{source:SOURCES[v],label:'Руководство семейства; сверить раздел',status:'Пример для профиля; требует сверки на модели'}}
evidence('create trunk access membership cpu-vlan','MikroTik',DOC.vlan,'Bridge VLAN Table');
evidence('ntp ntp-config','MikroTik',DOC.ntp,'NTP: клиент, servers, status');
evidence('nat','MikroTik',DOC.nat,'NAT');evidence('ospf','MikroTik',DOC.ospf,'OSPF');evidence('vrrp','MikroTik',DOC.vrrp,'VRRP');evidence('route static','MikroTik',DOC.route,'IP Routing');
evidence('logs syslog-config','MikroTik',DOC.log,'Log / remote actions');evidence('save','MikroTik',DOC.backup,'Backup');evidence('config export','MikroTik',DOC.console,'Configuration Management');evidence('snmp-check','MikroTik',DOC.snmp,'SNMP');
evidence('poe','Cisco',DOC.ciscoInterface,'Interface and Hardware: show power inline');evidence('snooping','Cisco',DOC.dai,'DHCP bindings / DAI statistics');
evidence('reloadtimer reloadcancel','Cisco',DOC.ciscoReload,'Device Setup: scheduling reload');evidence('replaceconfig','Cisco',DOC.ciscoReplace,'Configuration Replace / Rollback');evidence('replaceconfig','H3C',DOC.h3cRollback,'Configuration file management / replace');
evidence('ntp ntp-config vrrp poe errors resources create shutdown noshutdown svi storm','Eltex',SOURCES.Eltex,'MES 6.6.13.4: раздел по соответствующей функции');
evidence('mrp mrpcounter','SCALANCE',SOURCES.SCALANCE+'#page=506','CLI V4.4 · 9.4.4 Ring redundancy');evidence('fault','SCALANCE',SOURCES.SCALANCE+'#page=711','CLI V4.4 · 13.1.3 Faults');

SOURCES.Huawei="https://support.huawei.com/enterprise/en/doc/EDOC1100459384";
evidence("hsrp","Cisco","https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/xe-16-12/fhp-xe-16-12-book/fhp-hsrp.html","HSRP: show standby brief");

evidence("ports port","SCALANCE",SOURCES.SCALANCE+"#page=65","CLI V4.4 · show interfaces");
evidence("vlan","SCALANCE",SOURCES.SCALANCE+"#page=232","CLI V4.4 · VLAN");
evidence("membership","SCALANCE",SOURCES.SCALANCE+"#page=235","CLI V4.4 · show vlan port config");
evidence("mac","SCALANCE",SOURCES.SCALANCE+"#page=227","CLI V4.4 · MAC address table");
evidence("arp","SCALANCE",SOURCES.SCALANCE+"#page=468","CLI V4.4 · ARP");
evidence("lldp","SCALANCE",SOURCES.SCALANCE+"#page=68","CLI V4.4 · LLDP");
evidence("stp","SCALANCE",SOURCES.SCALANCE+"#page=285","CLI V4.4 · Spanning Tree");
evidence("lacp","SCALANCE",SOURCES.SCALANCE+"#page=281","CLI V4.4 · LACP neighbor / counters");
evidence("config portconfig","SCALANCE",SOURCES.SCALANCE+"#page=140","CLI V4.4 · running-config");
evidence("save","SCALANCE",SOURCES.SCALANCE+"#page=144","CLI V4.4 · write startup-config");
evidence("logs","SCALANCE",SOURCES.SCALANCE+"#page=712","CLI V4.4 · logbook");
evidence("version","SCALANCE",SOURCES.SCALANCE+"#page=62","CLI V4.4 · device information");
evidence("ip","SCALANCE",SOURCES.SCALANCE+"#page=67","CLI V4.4 · IP interface");
evidence("ntp","SCALANCE",SOURCES.SCALANCE+"#page=191","CLI V4.4 · NTP");
evidence("igmp","SCALANCE",SOURCES.SCALANCE+"#page=486","CLI V4.4 · IGMP groups");
evidence("mrpcounter","SCALANCE",SOURCES.SCALANCE+"#page=507","CLI V4.4 · Ring manager counters");

TASKS.find(t=>t.id==="errors").commands.SCALANCE="show interfaces counters";
evidence("errors","SCALANCE",SOURCES.SCALANCE+"#page=66","CLI V4.4 · Interface counters");

evidence("portconfig","Eltex",SOURCES.Eltex+"#page=146","MES 6.6.13.4 · с. 146: show running-config interfaces");

const IPV6_DOC={Cisco:'https://www.cisco.com/c/en/us/td/docs/ios/ipv6/command/reference/ipv6_book/ipv6_14.html',MikroTik:'https://help.mikrotik.com/docs/spaces/ROS/pages/40992815/IPv6+Neighbor+Discovery'};
addTask('ipv6-address','Проверить IPv6-адреса интерфейсов','IPv6','ipv6 slaac link local tentative dad','Сверь IPv6-адрес, длину префикса и состояние интерфейса. Link-local fe80:: нормален, но не обеспечивает связь с удалённой сетью.',{Cisco:'show ipv6 interface brief',Eltex:'show ipv6 interface brief',MikroTik:'/ipv6 address print detail'},'IPv6 должен поддерживаться конкретной моделью. Здесь просмотр адресов устройства; адрес клиента проверяй на самом клиенте.');
addTask('ipv6-neighbors','Проверить соседей IPv6 / NDP','IPv6','ipv6 ndp neighbors ns na mac','Кэш NDP связывает локального IPv6-соседа с MAC. Для удалённой сети нужен next hop; состояние STALE само по себе не означает неисправность.',{Cisco:'show ipv6 neighbors',Eltex:'show ipv6 neighbors vlan 120',MikroTik:'/ipv6 neighbor print'},'Eltex: пример кэша VLAN 120, этот VLAN должен быть явно выбран в задании. NS без NA: проверь соседа, VLAN и фильтрацию ICMPv6.').examTitle={Eltex:'Посмотреть IPv6-соседей в VLAN 120'};
addTask('ipv6-route','Проверить маршруты IPv6','IPv6','ipv6 route default gateway','Сверь маршрут назначения и ::/0, интерфейс и next hop. IPv4-маршруты не обеспечивают IPv6-доступ.',{Cisco:'show ipv6 route',Eltex:'show ipv6 route',MikroTik:'/ipv6 route print detail'},'Шлюз клиента, получаемый из RA, проверяй также на самом клиенте. Link-local next hop требует правильного исходящего интерфейса.');
addTask('ipv6-ra','Проверить параметры RA на шлюзе VLAN 120','IPv6','ipv6 ra router advertisement slaac prefix','На шлюзе сравни объявляемый префикс, A/L, lifetime и параметры ND. Факт получения RA клиентом подтверждай захватом у клиента.',{Cisco:'show ipv6 interface Vlan120',MikroTik:'/ipv6 nd print detail\n/ipv6 nd prefix print detail'},'Cisco: SVI Vlan120 должен существовать и поддерживать IPv6. RouterOS: настройки ND описывают отправку RA; их наличие не доказывает доставку. Для обычного SLAAC нужен пригодный /64 с A=1, для шлюза — ненулевой Router Lifetime.');
for(const id of ['ipv6-address','ipv6-neighbors','ipv6-route','ipv6-ra']){const t=TASKS.find(t=>t.id===id);for(const v of Object.keys(t.commands))evidence(id,v,v==='Eltex'?SOURCES.Eltex+'#page=195':IPV6_DOC[v],v==='Eltex'?'MES 6.6.13.4 · с. 195: IPv6':'IPv6 · сверить соответствующий раздел',v==='Eltex'||v==='Cisco'?'По руководству; на устройстве не проверено':'Пример RouterOS 7; сверить help на версии');}
HOST_TASKS.push(
{id:'host-ipv6',title:'IPv6: адреса, DAD и маршруты',description:'Проверь адреса и их состояние, выбранный интерфейс и ::/0. Учебный адрес замени реальным; 2001:db8::/32 предназначен для документации.',commands:{Windows:'Get-NetIPAddress -AddressFamily IPv6\nGet-NetRoute -AddressFamily IPv6',Linux:'ip -6 address\nip -6 route\nip -6 route get 2001:db8:120::10'},sources:{Windows:'https://learn.microsoft.com/en-us/powershell/module/nettcpip/get-netipaddress',Linux:'https://github.com/iproute2/iproute2/blob/main/man/man8/ip-route.8.in'},note:'Tentative — DAD ещё идёт; Duplicate/dadfailed — адрес не прошёл проверку. Для Linux с forwarding=1 приём RA зависит от accept_ra; не меняй sysctl наугад.'},
{id:'host-ipv6-neigh',title:'IPv6: кэш соседей',description:'Сравни IPv6, MAC, интерфейс и состояние соседа. Удалённый сервер обычно не появляется в локальном NDP-кэше.',commands:{Windows:'Get-NetNeighbor -AddressFamily IPv6',Linux:'ip -6 neigh'},sources:{Windows:'https://learn.microsoft.com/en-us/powershell/module/nettcpip/get-netneighbor',Linux:'https://github.com/iproute2/iproute2/blob/main/man/man8/ip-neighbour.8'},note:'STALE допустим. INCOMPLETE/FAILED вместе с повторными NS без NA требует проверки локального сегмента и соседа.'},
{id:'host-ipv6-ping',title:'IPv6: проверить связь и link-local',description:'Первый ping — к реальному IPv6-адресу вместо примера. Во втором подставь фактический link-local шлюза и индекс/имя интерфейса.',commands:{Windows:'ping -6 2001:db8:120::10\nping -6 fe80::1%12',Linux:'ping -6 -c 4 2001:db8:120::10\nping -6 -c 4 -I eth0 fe80::1'},sources:{Windows:'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ping',Linux:'https://github.com/iputils/iputils/blob/master/doc/ping.xml'},note:'Windows: индекс 12 — пример, найди свой через Get-NetIPInterface -AddressFamily IPv6. Linux: eth0 — пример. Неответ на ping может быть фильтрацией ICMP Echo, а не потерей всех IPv6-пакетов.'},
{id:'host-ipv6-ra',title:'IPv6: захват RA и NDP',description:'Начни захват, воспроизведи подключение клиента, затем останови. RA периодические: их отсутствие в слишком коротком захвате не доказывает сбой.',commands:{Linux:'sudo tcpdump -ni eth0 -vv "icmp6"',Windows:'pktmon start --capture --pkt-size 0\npktmon stop\npktmon etl2pcap PktMon.etl --out ipv6.pcapng'},sources:{Linux:'https://www.tcpdump.org/manpages/tcpdump.1.html',Windows:'https://learn.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon'},note:'Linux: Ctrl+C завершает захват. Windows: start → воспроизведение → stop → конвертация — отдельные этапы с правами администратора. Открой результат в Wireshark: icmpv6.type == 134 для RA, 133 для RS, 135/136 для NS/NA. Проверь Prefix Information A/L и Router Lifetime.'}
);

// Точная связь темы с командой: не подменять один протокол другим.
const auditedRelated={'ACL':'acl','SNMP':'snmp-check','SSH / Telnet':'ssh-check','Port Security / Storm Control':'security','SPAN / Port Mirroring':'mirror'};
const noDirectTask=new Set(['PTP / IEEE 1588','PRP / HSR','PROFIBUS','TFTP / SFTP','DNS','Modbus TCP','802.1X','QoS · 802.1p / DSCP']);
for(const p of PROTOCOLS){if(auditedRelated[p.title])p.related=auditedRelated[p.title];if(noDirectTask.has(p.title))delete p.related;}
TASKS.find(t=>t.id==='resources').examTitle={Eltex:'Проверить загрузку CPU'};
TASKS.find(t=>t.id==='save').examTitle={MikroTik:'Создать бинарную резервную копию before-change'};
// В заданиях с параметрами условия явно перечисляют учебные значения.
for(const t of TASKS){t.examContext ||= {};for(const [v,c] of Object.entries(t.commands)){
 const params=[...new Set(c.match(/(?:GigabitEthernet|gigabitethernet|fastethernet)\s*[0-9/]+(?:-\d+)?|(?:ether|sfp-sfpplus)\d+|bridge\d+|bond\d+|(?:\d{1,3}\.){3}\d{1,3}(?:\/\d+)?|TO-SW2(?:-GI[0-9/]+)?|OFFICE|before-change|remote-log|vlan120/g)||[])];
 if(params.length)t.examContext[v]='Учебные значения: '+params.join(', ')+'. Используй эти значения в данном примере.';
}}
const auditContexts={
 create:'VLAN 120, имя OFFICE; RouterOS: bridge1, tagged ether1 и ether2, записи VLAN ещё нет.',
 trunk:'VLAN 120. Cisco/Eltex/H3C: Gi1/0/1; Huawei: Gi0/0/1. SCALANCE: Fa0/1–2, полный tagged-список этого VLAN. RouterOS: существующая запись bridge1 VLAN 120, полный tagged-список ether1,ether2.',
 access:'VLAN 120. Cisco/Eltex/H3C: Gi1/0/5; Huawei: Gi0/0/5. SCALANCE: Fa0/1–2 tagged, Fa0/3 untagged и PVID 120. RouterOS: bridge1, ether1/2 tagged, ether5 untagged и PVID 120; запись VLAN уже есть.',
 svi:'VLAN 120 уже создан. IP 10.120.0.1/24. Cisco/Eltex: включи SVI административно; H3C/Huawei: интерфейс уже включён.',
 'lag-config':'Cisco: Gi1/0/1 и Gi1/0/2, группа 1, LACP active; затем Port-channel1 в режиме trunk. Начни с interface range.',
 mirror:'Cisco: сессия 1, источник Gi1/0/5 в обоих направлениях, порт назначения Gi1/0/24.',
 'syslog-config':'Сервер 10.120.0.50. Cisco: порог informational. RouterOS: новое действие remote-log и topics=info.',
 'cpu-vlan':'Существующая запись bridge1 VLAN 120: полный tagged-список bridge1,ether1,ether2. Создай интерфейс vlan120 на bridge1 и назначь 10.120.0.2/24.',
 'rstp-config':'Cisco: режим rapid-pvst. RouterOS: bridge1, protocol-mode=rstp.',
 membership:'H3C: покажи trunk-порты и VLAN 120. Cisco: покажи switchport и trunk. RouterOS: порты bridge и таблицу bridge VLAN.'
};
for(const [id,context] of Object.entries(auditContexts)){const t=TASKS.find(t=>t.id===id);for(const v of Object.keys(t.commands))t.examContext[v]=context;}
