// Учебный список сокращений. Поддержка реального CLI зависит от модели, версии и контекста.
const CLI_SHORTCUTS={Cisco:{'enable':['en'],'configure terminal':['conf t','config t'],'show vlan brief':['sh vlan br','sh vlan brief','show vlan br'],'show interfaces status':['sh int status','sh interfaces status'],'show interfaces trunk':['sh int trunk','sh interfaces trunk'],'show interfaces switchport':['sh int switchport'],'show ip interface brief':['sh ip int br','sh ip int brief'],'show ip route':['sh ip route'],'show ip arp':['sh ip arp'],'show running-config':['sh run','show run'],'show version':['sh ver'],'show logging':['sh logging'],'show spanning-tree':['sh spanning-tree'],'show etherchannel summary':['sh etherchannel summary'],'no shutdown':['no shut'],'shutdown':['shut']},H3C:{'display vlan':['dis vlan'],'display interface brief':['dis interface brief'],'display version':['dis version'],'display current-configuration':['dis current-configuration']}};
// Explicit training aliases, never arbitrary prefixes. Keep arguments and line order intact.
// SCALANCE CLI V4.4 §3.5.4 allows uniquely identifiable abbreviations.
Object.assign(CLI_SHORTCUTS,{
 Eltex:{'show vlan':['sh vlan'],'show interfaces status':['sh interfaces status'],'show interfaces counters':['sh interfaces counters'],'show arp':['sh arp'],'show mac address-table':['sh mac address-table'],'show lldp neighbors':['sh lldp neighbors'],'show running-config':['sh running-config'],'show version':['sh version'],'show ipv6 interface brief':['sh ipv6 interface brief'],'show ipv6 route':['sh ipv6 route'],'show ipv6 neighbors vlan 120':['sh ipv6 neighbors vlan 120']},
 SCALANCE:{'show vlan':['sh vlan'],'show interfaces status':['sh interfaces status'],'show interfaces counters':['sh interfaces counters'],'show lldp neighbors':['sh lldp neighbors'],'show mac-address-table':['sh mac-address-table'],'show running-config':['sh running-config'],'show spanning-tree':['sh spanning-tree']},
 Huawei:{'display vlan':['dis vlan'],'display interface brief':['dis interface brief'],'display version':['dis version','dis ver'],'display current-configuration':['dis current-configuration'],'display arp':['dis arp'],'display mac-address':['dis mac-address'],'display stp brief':['dis stp brief'],'display port vlan':['dis port vlan'],'display lldp neighbor brief':['dis lldp neighbor brief'],'display ip routing-table':['dis ip routing-table'],'system-view':['sys']}
});

function acceptedCommand(input,expected,os){const clean=s=>s.trim().toLowerCase().replace(/\s+/g,' ').replace(/\s*\/\s*/g,'/');if(clean(input)===clean(expected))return true;const a=input.trim().split(/\r?\n/).map(clean),b=expected.trim().split(/\r?\n/).map(clean);return a.length===b.length&&a.every((line,i)=>line===b[i]||(CLI_SHORTCUTS[os]?.[b[i]]||[]).includes(line))}
function examDistractors(task,vendor){const seen=new Set([task.commands[vendor]]),pool=TASKS.filter(t=>t.id!==task.id&&t.quiz!==false&&t.commands[vendor]);const same=shuffle(pool.filter(t=>t.category===task.category)),other=shuffle(pool.filter(t=>t.category!==task.category));return [...same,...other].filter(t=>{const c=t.commands[vendor];if(seen.has(c))return false;seen.add(c);return true}).slice(0,3)}
